### ISSUE TITLE
use Approximate string matching when searching

### ISSUE THREAD

**Issue by ctf0** [jacobdufault/vscode-fuzzy-search#2]
atm the text have to be exact , but with approximate matching it will be closer to the quick open panel

**Comment by jacobdufault** [comment]
May be possible, but could be very difficult to accomplish the desired UX due to API limitations. The current extension just uses vscode's built-in fuzzy filtering. I believe you can have a custom input box now that dynamically updates the list of results, so it might be possible to do custom filtering.
